version: 2
updates:
  # Enable version updates for Python in web directory
  - package-ecosystem: "pip"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      # Trigger manual scan
    open-pull-requests-limit: 10
    reviewers:
      - "t288matt"
    assignees:
      - "t288matt"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "web"
    # Group minor and patch updates together
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Ignore major version updates for now (can be enabled later)
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major" 