version: '3.8'

services:
  atc-conflict:
    build: .
    ports:
      - "5000:5000"  # Web interface
      - "8000:8000"  # Animation server
    volumes:
      - ./uploads:/app/uploads:rw  # Persistent uploads
      - ./temp:/app/temp:rw  # Processing results
      - ./xml_files:/app/xml_files:rw  # XML storage
      - ./logs:/app/logs:rw  # Application logs
    environment:
      # Application Settings
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - FLASK_APP=web/app.py
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - LOG_FILE=/app/logs/app.log
      
      # Security Settings
      - SECRET_KEY=your-production-secret-key-here
      - CORS_ORIGINS=http://localhost:5000,http://localhost:8000
      
      # Conflict Detection Parameters
      - LATERAL_SEPARATION_THRESHOLD=3.0
      - VERTICAL_SEPARATION_THRESHOLD=900
      - MIN_ALTITUDE_THRESHOLD=5000
      - NO_CONFLICT_AIRPORT_DISTANCES=YSSY/35,YSCB/15
      
      # Departure Scheduling Parameters
      - MIN_DEPARTURE_SEPARATION_MINUTES=2
      - MIN_SAME_ROUTE_SEPARATION_MINUTES=5
      - BATCH_SIZE=1
      
      # Route Interpolation Parameters
      - INTERPOLATION_SPACING_NM=1.5
      
      # Scheduling Optimization Parameters
      - TIME_TOLERANCE_MINUTES=2
      - MAX_DEPARTURE_TIME_MINUTES=120
      - DEPARTURE_TIME_STEP_MINUTES=5
      - TRANSITION_ALTITUDE_FT=10500
      
      # Web Interface Parameters
      - WEB_PORT=5000
      - ANIMATION_PORT=8000
      - MAX_FILE_SIZE_BYTES=16777216
      - UPLOAD_TIMEOUT_MS=30000
      - MAX_PROCESSING_TIME_MS=300000
      
      # UI Settings
      - MESSAGE_DISPLAY_TIME_MS=5000
      - AUTO_REFRESH_INTERVAL_MS=3000
      - PROGRESS_UPDATE_INTERVAL_MS=1000
      
      # Processing Settings
      - MAX_RETRIES=3
      - STATUS_CHECK_INTERVAL_MS=1000
      - VALIDATION_CACHE_TIMEOUT_SEC=3600
      
      # File System Settings
      - UPLOAD_FOLDER=/app/uploads
      - TEMP_FOLDER=/app/temp
      - ANIMATION_FOLDER=/app/animation
      
      # Animation Parameters
      - DEFAULT_SIMULATION_SPEED=48
      - MIN_SIMULATION_SPEED=-120
      - MAX_SIMULATION_SPEED=120
      
      # Mathematical Constants
      - EARTH_RADIUS_NM=3440.065
      - FEET_TO_NM_CONVERSION=6076.12
      
      # Performance Settings
      - WORKER_PROCESSES=4
      - WORKER_CONNECTIONS=1000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

volumes:
  uploads:
  temp:
  xml_files:
  logs: 