services:
  atc-conflict:
    container_name: vatsim-chaos
    image: ghcr.io/t288matt/vatsim-chaos:latest
    ports:
      - "5000:5000"  # Web interface
    volumes:
      - ./xml_files:/app/xml_files:rw  # XML storage
    env_file:
      - docker.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    # Traefik integration
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vatsim-chaos.entrypoints=http"
      - "traefik.http.routers.vatsim-chaos.rule=Host(`vc.mpengor.com`)"
      - "traefik.http.middlewares.vatsim-chaos-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vatsim-chaos.middlewares=vatsim-chaos-https-redirect"
      - "traefik.http.routers.vatsim-chaos-secure.entrypoints=https"
      - "traefik.http.routers.vatsim-chaos-secure.rule=Host(`vc.mpengor.com`)"
      - "traefik.http.routers.vatsim-chaos-secure.tls=true"
      - "traefik.http.routers.vatsim-chaos-secure.service=vatsim-chaos"
      - "traefik.http.services.vatsim-chaos.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true 